
name: Build and Deploy Dub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: List workspace packages
        run: pnpm list --depth 1

      - name: Install dependencies
        run: pnpm install

      - name: Export Dub (Next.js static site)
        run: pnpm --filter web build
        
      - name: List contents of apps/web
        run: ls -la apps/web
        
      - name: List contents of apps/web/out
        run: ls -la apps/web/out

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "apps/web"
          output_location: "apps/web/out"
          skip_app_build: true
